project_id: 12345 # found in the project settings or address bar in Tracker
token: 123abc123abc123abc123abc # found on your profile page in Tracker
requested_by: Johnny Hashrocket # must be a user on the project
ssl: true # set to true if the project has ssl required
